name: Windows PowerShell
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -value 1
          shell: pwsh
