name: Windows PowerShell
on: [workflow_dispatch]

jobs:
  local-job:
    runs-on: self-hosted
    steps:
      - name: example-step
        run: echo "Hello World!"
      - name: print-ENV
        run: "[System.Environment]::GetEnvironmentVariables()"
      - name: print env variables from command prompt
        shell: cmd
        run: | 
          echo %PATH%
          echo %JAVA_HOME%
          echo %MAVEN_HOME%
